version: '3.8'
services:
  gcopy:
    container_name: gcopy
    image: llaoj/gcopy
    restart: always
    ports:
    - "3376:3376"
    command: ["--app-key=<app-key>", "--smtp-host=<smtp-host>", "--smtp-port=<smtp-port>", "--smtp-username=<smtp-username>", "--smtp-password=<smtp-password>", "--smtp-ssl"]

  gcopy-frontend:
    container_name: gcopy-frontend
    image: llaoj/gcopy-frontend
    restart: always
    ports:
    - "3375:3375"
    volumes:
    - ./frontend/.env.production:/app/.env.production
    depends_on:
    - gcopy